[package]
name = "git_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.20.1"
clap = { version = "4.1", features = ["derive"] }
chrono = { version = "0.4.40", features = ["serde"] }
rand = "0.9.1"
regex = "1.7"
reqwest = { version = "0.12.19", features = ["json", "blocking"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
dotenv = "0.15.0"
