name: Test the pachaged binart

on:
  push:
    branches: '**' 
    tags:
      - "v*"
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: 🦀 Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt
      - run: cargo test --all